# Generated by Django 5.2.7 on 2025-10-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_order_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='chosen_product',
        ),
        migrations.AddField(
            model_name='order',
            name='all_product',
            field=models.ManyToManyField(related_name='orders', through='api.OrderItem', to='api.product'),
        ),
    ]
