# Generated by Django 5.2.7 on 2025-10-22 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_product_orderitem_chosen_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='all_product',
            new_name='products',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='chosen_product',
            new_name='product',
        ),
    ]
